name: unit test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: npx hardhat test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Environment
      uses: actions/setup-node@v3
    - name: Install github-action configuration
      run: cp .github/hardhat.config.ts .
    - name: Test
      uses: ambersun1234/hardhat-test-action@v1
      with:
        network: hardhat
